package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Вход в МС")
    void generatedTest() {
        step("Открыть \"https://online.moysklad.ru/\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести логин \"admin@dborodin23\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Ввести пароль \"123123\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать кнопку \"Войти\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить авторизацию", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://online.moysklad.ru/'", () ->
            open("https://online.moysklad.ru/"));

        step("Page title should have text 'Вход в МойСклад - Проверка логина и пароля'", () -> {
            String expectedTitle = "Вход в МойСклад - Проверка логина и пароля";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://online.moysklad.ru/'", () ->
            open("https://online.moysklad.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}